<AddTasksScreen>:
    id: tasks
    AddTasksScreenCanvas:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        FloatLayout:
            MDTopAppBar:
                type: "small"
                size_hint_x: 1
                pos_hint: {"center_x": .5, "center_y": 0.96}
                MDTopAppBarLeadingButtonContainer:
                    MDActionTopAppBarButton:
                        icon: "home"
                        on_press: app.root.current = 'home'

            Label:
                text: "Add a Task"
                font_name: "CustomFont"
                font_size: "24sp"
                size_hint: None, None
                size: self.texture_size
                pos_hint: {"center_x": 0.5, "center_y": 0.96}
                color: 0, 0, 0, 1


            Label:
                text: "Task Name:"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.82}
                padding: "4dp", "4dp"

            MDTextField:
                id: task_name
                font_name: "CustomFont"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.76}
                mode: "outlined"
                size_hint_x: 0.4
                required: True
                MDTextFieldHintText:
                    text: "Task name"
                    font_name: "CustomFont"  # Add this to apply font_name

            Label:
                text: "Due Date (YYYY/MM/DD):"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.70}
                padding: "4dp", "4dp"

            MDTextField:
                id: due_date
                font_name: "CustomFont"
                mode: "outlined"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.64}
                size_hint_x: 0.4
                required: True
                validator: "date"
                date_format: "yyyy/mm/dd"
                MDTextFieldHintText:
                    text: "YYYY/MM/DD"
                    font_name: "CustomFont"  # Add this to apply font_name
            Label:
                text: "Start Time (HH:MM):"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.58}
                padding: "4dp", "4dp"

            MDTextField:
                id: start_time
                font_name: "CustomFont"
                mode: "outlined"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.52}
                size_hint_x: 0.4
                required: True
                MDTextFieldHintText:
                    text: "start time: HH:MM"
                    font_name: "CustomFont"

            Label:
                text: "End Time (HH:MM):"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.46}
                padding: "4dp", "4dp"

            MDTextField:
                id: end_time
                font_name: "CustomFont"
                mode: "outlined"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.40}
                size_hint_x: 0.4
                required: True
                MDTextFieldHintText:
                    text: "end time: HH:MM"
                    font_name: "CustomFont"

            MDTextField:
                id: start_ampm
                text: "AM"
                hint_text: "AM/PM"
                mode: "outlined"
                icon_right: "menu-down"
                readonly: True
                size_hint_x: 0.1
                pos_hint: {"center_x": 0.78, "center_y": 0.52}
                on_touch_down: app.open_ampm_menu("start")

            MDTextField:
                id: end_ampm
                text: "AM"
                hint_text: "AM/PM"
                mode: "outlined"
                icon_right: "menu-down"
                readonly: True
                size_hint_x: 0.1
                pos_hint: {"center_x": 0.78, "center_y": 0.40}
                on_touch_down: app.open_ampm_menu("end")

            Label:
                text: "Priority:"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.34}
                padding: "4dp", "4dp"

            MDTextField:
                id: priority
                font_name: "CustomFont"
                mode: "outlined"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.28}
                size_hint_x: 0.4
                required: True
                MDTextFieldHintText:
                    text: "Priority"
                    font_name: "CustomFont"  # Add this to apply font_name

            Label:
                text: "Description:"
                font_name: "CustomFont"
                font_size: "20sp"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.22}
                padding: "4dp", "4dp"

            MDTextField:
                id: description
                font_name: "CustomFont"
                mode: "outlined"
                adaptive_size: True
                pos_hint: {"center_x": 0.5, "center_y": 0.16}
                size_hint_x: 0.4
                required: True
                MDTextFieldHintText:
                    text: "Description"
                    font_name: "CustomFont"  # Add this to apply font_name

            Button:
                text: "Save Task"
                font_size: "20sp"
                font_name: "CustomFont"
                size_hint: None, None
                size: 200, 48
                pos_hint: {"center_x": 0.5, "center_y": 0.05}
                on_press: app.save_task()

            Image:
                source: 'assets/fox_2.png'
                size_hint: None, None
                size: 500, 500  # Adjust the size as needed
                pos_hint: {"x": -0.08, "bottom": 0}