<ViewTasksScreen>:
    BoxLayout:
        orientation: 'vertical'

        ScrollView:
            BoxLayout:
                id: task_list
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                padding: 10
                spacing: 10

        Button:
            text: "Back"
            size_hint: None, None
            size: 200, 40
            pos_hint: {"center_x": 0.5}
            on_press: app.go_home()